### ISSUE TITLE
Why PSNR is low？

### ISSUE THREAD

**Issue by hmppt** [ganji15/HiGANplus#10]
I read the paper, and i have a question about the metric. I don't have deep research on font image generation, but i found that the psnr in the paper is very low(less than 20). Does this mean that the generated image is not very similar to the original image?

**Comment by ganji15** [comment]
Hi, @hmppt

Since handwriting is very arbitrary, the synthetic handwriting image is not entirely spatially aligned (pixel-by-pixel) with the original handwriting image (though their styles are similar and textual contents are exactly the same). Perhaps this is the reason why the PSNR is very low.

Thanks!

**Comment by hmppt** [comment]
Please allow me to ask again. Is there currently an objective indicator for font style consistency, or it only be seen with the human eye?

**Comment by ganji15** [comment]
Hi, @hmppt

In the paper, we use the *Writer Identification Error Rate (WIER)* to indicate the handwriting style transferability of GANs, which is the number of writer identification errors divided by that of the total words/samples. By the way, we mainly use the IS & FID to evaluate the visual quality of synthetic images.

Thanks!
