### ISSUE TITLE
Able to reproduce one specific calligraphic style?

### ISSUE THREAD

**Issue by SB2020-eye** [ganji15/HiGANplus#2]
Hello.

I have images of one particular calligraphic style which I am trying to reproduce (so that my text put in creates an image of the same words in the calligraphic style).

The section in your paper on "Imitating Handwriting in the Wild" made me wonder if this might be possible somehow, utilizing HIGANplus.

Would it be possible?

(And if so, would I use a model trained from the GNHK dataset, or would I produce my own model using the images of the style I wish to reproduce?

And if I would use a model from the GNHK dataset, do you have an already trained model available?)

**Comment by ganji15** [comment]
Hi @SB2020-eye ,

It is possible to reproduce one specific calligraphic style by utilizing HIGANplus. 

The solutions may be different depending on your  given calligraphic style:
1. if the given style is grey-scaled handwriting images that are similar to IAM, you can directly use the released pre-trained model of HiGANplus to reproduce handwriting;
2. if the given style is handwriting images in the wild, you may need to train a new HiGANplus model using the corresponding training data (such as GNHK or IMGUR5K).

Additionally, the released code can only synthesize grey-scaled images since the channel of output images is 1 (instead of 3). Therefore, you have to slightly revise the code to make HiGANplus output RGB images (of 3 channels) and then re-train the model using the corresponding reference images.

Thanks!

**Comment by nathanshipley** [comment]
Hello!  Thank you for sharing your great work!  

Are you able to provide any more guidance about how to specify the given calligraphic style to reproduce?

Assume I have a handwriting sample PNG image file in the same format as IAM:  Is there a way to actually specify that the architecture use this image as the target style for new input text?

I'm successfully running your code and generating samples using `eval_demo.py`.  It looks very nice; just curious how to control.

**Comment by enoreyes** [comment]
Hi @ganji15 i also have interest in guidance on reproducing a specific style given a prior sample - the same problem as @nathanshipley

**Comment by ganji15** [comment]
@enoreyes @nathanshipley @SB2020-eye 

I have updated the code so that you can reproduce specific calligraphic styles from images (e.g., PNG, JPG). The steps are given as follow:

1. Download the newest repository ``` git clone https://github.com/ganji15/HiGANplus.git```
2. Put your reference images into the directory ```./data/image_samples/```
3. Run the command
    ```python eval_demo.py --config ./configs/gan_image.yml --ckpt ./pretrained/deploy_HiGAN+.pth --mode style```

After that, you can reproduce specific styles given prior images/samples.

![demo](https://user-images.githubusercontent.com/3733327/217192418-bf0e695f-1bc9-44b1-a0ee-071efd4fe04c.png)

**Comment by nathanshipley** [comment]
Wow!  Thank you so much!  Just tested here and it's working.  Really appreciate it.
